[package]
name = "line-counter"
version = "0.1.0"
authors = ["Alex Gaynor <alex@alloy.us>"]
edition = "2018"

[dependencies]
bytecount = { version = "0.6", features = ["runtime-dispatch-simd"] }
nix = { version = "0.29", features = ["fs", "mman"] }
num_cpus = "1"
rayon = "1"
